/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-01 15:32:38 UTC)
 * on 2013-08-03 at 09:40:23 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.getFriendEndpoint;

/**
 * Service definition for GetFriendEndpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GetFriendEndpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class GetFriendEndpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://itsptestapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "getFriendEndpoint/v1/GetFriendResultDto/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public GetFriendEndpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  GetFriendEndpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the GetFriendV1Endpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code GetFriendEndpoint getFriendEndpoint = new GetFriendEndpoint(...);}
   *   {@code GetFriendEndpoint.GetFriendV1Endpoint.List request = getFriendEndpoint.getFriendV1Endpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public GetFriendV1Endpoint getFriendV1Endpoint() {
    return new GetFriendV1Endpoint();
  }

  /**
   * The "getFriendV1Endpoint" collection of methods.
   */
  public class GetFriendV1Endpoint {

    /**
     * Create a request for the method "getFriendV1Endpoint.getFriendFrom".
     *
     * This request holds the parameters needed by the the getFriendEndpoint server.  After setting any
     * optional parameters, call the {@link GetFriendFrom#execute()} method to invoke the remote
     * operation.
     *
     * @param email
     * @return the request
     */
    public GetFriendFrom getFriendFrom(java.lang.String email) throws java.io.IOException {
      GetFriendFrom result = new GetFriendFrom(email);
      initialize(result);
      return result;
    }

    public class GetFriendFrom extends GetFriendEndpointRequest<com.google.api.services.getFriendEndpoint.model.GetFriendResultV1Dto> {

      private static final String REST_PATH = "getFriendFrom";

      /**
       * Create a request for the method "getFriendV1Endpoint.getFriendFrom".
       *
       * This request holds the parameters needed by the the getFriendEndpoint server.  After setting
       * any optional parameters, call the {@link GetFriendFrom#execute()} method to invoke the remote
       * operation. <p> {@link GetFriendFrom#initialize(com.google.api.client.googleapis.services.Abstra
       * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param email
       * @since 1.13
       */
      protected GetFriendFrom(java.lang.String email) {
        super(GetFriendEndpoint.this, "GET", REST_PATH, null, com.google.api.services.getFriendEndpoint.model.GetFriendResultV1Dto.class);
        this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetFriendFrom setAlt(java.lang.String alt) {
        return (GetFriendFrom) super.setAlt(alt);
      }

      @Override
      public GetFriendFrom setFields(java.lang.String fields) {
        return (GetFriendFrom) super.setFields(fields);
      }

      @Override
      public GetFriendFrom setKey(java.lang.String key) {
        return (GetFriendFrom) super.setKey(key);
      }

      @Override
      public GetFriendFrom setOauthToken(java.lang.String oauthToken) {
        return (GetFriendFrom) super.setOauthToken(oauthToken);
      }

      @Override
      public GetFriendFrom setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetFriendFrom) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetFriendFrom setQuotaUser(java.lang.String quotaUser) {
        return (GetFriendFrom) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetFriendFrom setUserIp(java.lang.String userIp) {
        return (GetFriendFrom) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String email;

      /**

       */
      public java.lang.String getEmail() {
        return email;
      }

      public GetFriendFrom setEmail(java.lang.String email) {
        this.email = email;
        return this;
      }

      @Override
      public GetFriendFrom set(String parameterName, Object value) {
        return (GetFriendFrom) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "getFriendV1Endpoint.getFriendTo".
     *
     * This request holds the parameters needed by the the getFriendEndpoint server.  After setting any
     * optional parameters, call the {@link GetFriendTo#execute()} method to invoke the remote
     * operation.
     *
     * @param email
     * @return the request
     */
    public GetFriendTo getFriendTo(java.lang.String email) throws java.io.IOException {
      GetFriendTo result = new GetFriendTo(email);
      initialize(result);
      return result;
    }

    public class GetFriendTo extends GetFriendEndpointRequest<com.google.api.services.getFriendEndpoint.model.GetFriendResultV1Dto> {

      private static final String REST_PATH = "getFriendTo";

      /**
       * Create a request for the method "getFriendV1Endpoint.getFriendTo".
       *
       * This request holds the parameters needed by the the getFriendEndpoint server.  After setting
       * any optional parameters, call the {@link GetFriendTo#execute()} method to invoke the remote
       * operation. <p> {@link
       * GetFriendTo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param email
       * @since 1.13
       */
      protected GetFriendTo(java.lang.String email) {
        super(GetFriendEndpoint.this, "GET", REST_PATH, null, com.google.api.services.getFriendEndpoint.model.GetFriendResultV1Dto.class);
        this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetFriendTo setAlt(java.lang.String alt) {
        return (GetFriendTo) super.setAlt(alt);
      }

      @Override
      public GetFriendTo setFields(java.lang.String fields) {
        return (GetFriendTo) super.setFields(fields);
      }

      @Override
      public GetFriendTo setKey(java.lang.String key) {
        return (GetFriendTo) super.setKey(key);
      }

      @Override
      public GetFriendTo setOauthToken(java.lang.String oauthToken) {
        return (GetFriendTo) super.setOauthToken(oauthToken);
      }

      @Override
      public GetFriendTo setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetFriendTo) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetFriendTo setQuotaUser(java.lang.String quotaUser) {
        return (GetFriendTo) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetFriendTo setUserIp(java.lang.String userIp) {
        return (GetFriendTo) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String email;

      /**

       */
      public java.lang.String getEmail() {
        return email;
      }

      public GetFriendTo setEmail(java.lang.String email) {
        this.email = email;
        return this;
      }

      @Override
      public GetFriendTo set(String parameterName, Object value) {
        return (GetFriendTo) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link GetFriendEndpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link GetFriendEndpoint}. */
    @Override
    public GetFriendEndpoint build() {
      return new GetFriendEndpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GetFriendEndpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGetFriendEndpointRequestInitializer(
        GetFriendEndpointRequestInitializer getfriendendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(getfriendendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
