/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-01 15:32:38 UTC)
 * on 2013-08-03 at 09:39:59 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.getShareTimeEndpoint;

/**
 * Service definition for GetShareTimeEndpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GetShareTimeEndpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class GetShareTimeEndpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://itsptestapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "getShareTimeEndpoint/v1/getsharetimev1resultdto/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public GetShareTimeEndpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  GetShareTimeEndpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the GetShareTimeV1Endpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code GetShareTimeEndpoint getShareTimeEndpoint = new GetShareTimeEndpoint(...);}
   *   {@code GetShareTimeEndpoint.GetShareTimeV1Endpoint.List request = getShareTimeEndpoint.getShareTimeV1Endpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public GetShareTimeV1Endpoint getShareTimeV1Endpoint() {
    return new GetShareTimeV1Endpoint();
  }

  /**
   * The "getShareTimeV1Endpoint" collection of methods.
   */
  public class GetShareTimeV1Endpoint {

    /**
     * Create a request for the method "getShareTimeV1Endpoint.getShareTime".
     *
     * This request holds the parameters needed by the the getShareTimeEndpoint server.  After setting
     * any optional parameters, call the {@link GetShareTime#execute()} method to invoke the remote
     * operation.
     *
     * @param emailCSV
     * @param startTime
     * @param finishTime
     * @return the request
     */
    public GetShareTime getShareTime(java.lang.String emailCSV, java.lang.Long startTime, java.lang.Long finishTime) throws java.io.IOException {
      GetShareTime result = new GetShareTime(emailCSV, startTime, finishTime);
      initialize(result);
      return result;
    }

    public class GetShareTime extends GetShareTimeEndpointRequest<com.google.api.services.getShareTimeEndpoint.model.GetShareTimeV1ResultDto> {

      private static final String REST_PATH = "{emailCSV}/{startTime}/{finishTime}";

      /**
       * Create a request for the method "getShareTimeV1Endpoint.getShareTime".
       *
       * This request holds the parameters needed by the the getShareTimeEndpoint server.  After setting
       * any optional parameters, call the {@link GetShareTime#execute()} method to invoke the remote
       * operation. <p> {@link
       * GetShareTime#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param emailCSV
       * @param startTime
       * @param finishTime
       * @since 1.13
       */
      protected GetShareTime(java.lang.String emailCSV, java.lang.Long startTime, java.lang.Long finishTime) {
        super(GetShareTimeEndpoint.this, "GET", REST_PATH, null, com.google.api.services.getShareTimeEndpoint.model.GetShareTimeV1ResultDto.class);
        this.emailCSV = com.google.api.client.util.Preconditions.checkNotNull(emailCSV, "Required parameter emailCSV must be specified.");
        this.startTime = com.google.api.client.util.Preconditions.checkNotNull(startTime, "Required parameter startTime must be specified.");
        this.finishTime = com.google.api.client.util.Preconditions.checkNotNull(finishTime, "Required parameter finishTime must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetShareTime setAlt(java.lang.String alt) {
        return (GetShareTime) super.setAlt(alt);
      }

      @Override
      public GetShareTime setFields(java.lang.String fields) {
        return (GetShareTime) super.setFields(fields);
      }

      @Override
      public GetShareTime setKey(java.lang.String key) {
        return (GetShareTime) super.setKey(key);
      }

      @Override
      public GetShareTime setOauthToken(java.lang.String oauthToken) {
        return (GetShareTime) super.setOauthToken(oauthToken);
      }

      @Override
      public GetShareTime setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetShareTime) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetShareTime setQuotaUser(java.lang.String quotaUser) {
        return (GetShareTime) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetShareTime setUserIp(java.lang.String userIp) {
        return (GetShareTime) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String emailCSV;

      /**

       */
      public java.lang.String getEmailCSV() {
        return emailCSV;
      }

      public GetShareTime setEmailCSV(java.lang.String emailCSV) {
        this.emailCSV = emailCSV;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.Long startTime;

      /**

       */
      public java.lang.Long getStartTime() {
        return startTime;
      }

      public GetShareTime setStartTime(java.lang.Long startTime) {
        this.startTime = startTime;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.Long finishTime;

      /**

       */
      public java.lang.Long getFinishTime() {
        return finishTime;
      }

      public GetShareTime setFinishTime(java.lang.Long finishTime) {
        this.finishTime = finishTime;
        return this;
      }

      @Override
      public GetShareTime set(String parameterName, Object value) {
        return (GetShareTime) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link GetShareTimeEndpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link GetShareTimeEndpoint}. */
    @Override
    public GetShareTimeEndpoint build() {
      return new GetShareTimeEndpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GetShareTimeEndpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGetShareTimeEndpointRequestInitializer(
        GetShareTimeEndpointRequestInitializer getsharetimeendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(getsharetimeendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
