/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-01 15:32:38 UTC)
 * on 2013-08-03 at 09:40:34 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.friendEndpoint;

/**
 * Service definition for FriendEndpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link FriendEndpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class FriendEndpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://itsptestapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "friendEndpoint/v1/Friendship/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public FriendEndpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  FriendEndpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the FriendV1Endpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code FriendEndpoint friendEndpoint = new FriendEndpoint(...);}
   *   {@code FriendEndpoint.FriendV1Endpoint.List request = friendEndpoint.friendV1Endpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public FriendV1Endpoint friendV1Endpoint() {
    return new FriendV1Endpoint();
  }

  /**
   * The "friendV1Endpoint" collection of methods.
   */
  public class FriendV1Endpoint {

    /**
     * Create a request for the method "friendV1Endpoint.friendship".
     *
     * This request holds the parameters needed by the the friendEndpoint server.  After setting any
     * optional parameters, call the {@link Friendship#execute()} method to invoke the remote operation.
     *
     * @param email
     * @param myemail
     * @return the request
     */
    public Friendship friendship(java.lang.String email, java.lang.String myemail) throws java.io.IOException {
      Friendship result = new Friendship(email, myemail);
      initialize(result);
      return result;
    }

    public class Friendship extends FriendEndpointRequest<com.google.api.services.friendEndpoint.model.FriendResultV1Dto> {

      private static final String REST_PATH = "{email}/{myemail}";

      /**
       * Create a request for the method "friendV1Endpoint.friendship".
       *
       * This request holds the parameters needed by the the friendEndpoint server.  After setting any
       * optional parameters, call the {@link Friendship#execute()} method to invoke the remote
       * operation. <p> {@link
       * Friendship#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param email
       * @param myemail
       * @since 1.13
       */
      protected Friendship(java.lang.String email, java.lang.String myemail) {
        super(FriendEndpoint.this, "POST", REST_PATH, null, com.google.api.services.friendEndpoint.model.FriendResultV1Dto.class);
        this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
        this.myemail = com.google.api.client.util.Preconditions.checkNotNull(myemail, "Required parameter myemail must be specified.");
      }

      @Override
      public Friendship setAlt(java.lang.String alt) {
        return (Friendship) super.setAlt(alt);
      }

      @Override
      public Friendship setFields(java.lang.String fields) {
        return (Friendship) super.setFields(fields);
      }

      @Override
      public Friendship setKey(java.lang.String key) {
        return (Friendship) super.setKey(key);
      }

      @Override
      public Friendship setOauthToken(java.lang.String oauthToken) {
        return (Friendship) super.setOauthToken(oauthToken);
      }

      @Override
      public Friendship setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Friendship) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Friendship setQuotaUser(java.lang.String quotaUser) {
        return (Friendship) super.setQuotaUser(quotaUser);
      }

      @Override
      public Friendship setUserIp(java.lang.String userIp) {
        return (Friendship) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String email;

      /**

       */
      public java.lang.String getEmail() {
        return email;
      }

      public Friendship setEmail(java.lang.String email) {
        this.email = email;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.String myemail;

      /**

       */
      public java.lang.String getMyemail() {
        return myemail;
      }

      public Friendship setMyemail(java.lang.String myemail) {
        this.myemail = myemail;
        return this;
      }

      @Override
      public Friendship set(String parameterName, Object value) {
        return (Friendship) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link FriendEndpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link FriendEndpoint}. */
    @Override
    public FriendEndpoint build() {
      return new FriendEndpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link FriendEndpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setFriendEndpointRequestInitializer(
        FriendEndpointRequestInitializer friendendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(friendendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
