/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-01 15:32:38 UTC)
 * on 2013-08-03 at 09:39:59 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.getShareTimeEndpoint.model;

/**
 * Model definition for GroupScheduleV1Dto.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GroupScheduleV1Dto extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long finishTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long startTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<UserV1Dto> userList;

  static {
    // hack to force ProGuard to consider UserV1Dto used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(UserV1Dto.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFinishTime() {
    return finishTime;
  }

  /**
   * @param finishTime finishTime or {@code null} for none
   */
  public GroupScheduleV1Dto setFinishTime(java.lang.Long finishTime) {
    this.finishTime = finishTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStartTime() {
    return startTime;
  }

  /**
   * @param startTime startTime or {@code null} for none
   */
  public GroupScheduleV1Dto setStartTime(java.lang.Long startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<UserV1Dto> getUserList() {
    return userList;
  }

  /**
   * @param userList userList or {@code null} for none
   */
  public GroupScheduleV1Dto setUserList(java.util.List<UserV1Dto> userList) {
    this.userList = userList;
    return this;
  }

  @Override
  public GroupScheduleV1Dto set(String fieldName, Object value) {
    return (GroupScheduleV1Dto) super.set(fieldName, value);
  }

  @Override
  public GroupScheduleV1Dto clone() {
    return (GroupScheduleV1Dto) super.clone();
  }

}
