/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-01 15:32:38 UTC)
 * on 2013-08-03 at 09:39:38 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.scheduleEndpoint;

/**
 * Service definition for ScheduleEndpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ScheduleEndpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class ScheduleEndpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://itsptestapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "scheduleEndpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public ScheduleEndpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  ScheduleEndpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the ScheduleV1EndPoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code ScheduleEndpoint scheduleEndpoint = new ScheduleEndpoint(...);}
   *   {@code ScheduleEndpoint.ScheduleV1EndPoint.List request = scheduleEndpoint.scheduleV1EndPoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public ScheduleV1EndPoint scheduleV1EndPoint() {
    return new ScheduleV1EndPoint();
  }

  /**
   * The "scheduleV1EndPoint" collection of methods.
   */
  public class ScheduleV1EndPoint {

    /**
     * Create a request for the method "scheduleV1EndPoint.createSchedule".
     *
     * This request holds the parameters needed by the the scheduleEndpoint server.  After setting any
     * optional parameters, call the {@link CreateSchedule#execute()} method to invoke the remote
     * operation.
     *
     * @param startTime
     * @param finishTime
     * @param email
     * @return the request
     */
    public CreateSchedule createSchedule(java.lang.Long startTime, java.lang.Long finishTime, java.lang.String email) throws java.io.IOException {
      CreateSchedule result = new CreateSchedule(startTime, finishTime, email);
      initialize(result);
      return result;
    }

    public class CreateSchedule extends ScheduleEndpointRequest<com.google.api.services.scheduleEndpoint.model.ScheduleResultV1Dto> {

      private static final String REST_PATH = "createSchedule/{startTime}/{finishTime}/{email}";

      /**
       * Create a request for the method "scheduleV1EndPoint.createSchedule".
       *
       * This request holds the parameters needed by the the scheduleEndpoint server.  After setting any
       * optional parameters, call the {@link CreateSchedule#execute()} method to invoke the remote
       * operation. <p> {@link CreateSchedule#initialize(com.google.api.client.googleapis.services.Abstr
       * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param startTime
       * @param finishTime
       * @param email
       * @since 1.13
       */
      protected CreateSchedule(java.lang.Long startTime, java.lang.Long finishTime, java.lang.String email) {
        super(ScheduleEndpoint.this, "POST", REST_PATH, null, com.google.api.services.scheduleEndpoint.model.ScheduleResultV1Dto.class);
        this.startTime = com.google.api.client.util.Preconditions.checkNotNull(startTime, "Required parameter startTime must be specified.");
        this.finishTime = com.google.api.client.util.Preconditions.checkNotNull(finishTime, "Required parameter finishTime must be specified.");
        this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      }

      @Override
      public CreateSchedule setAlt(java.lang.String alt) {
        return (CreateSchedule) super.setAlt(alt);
      }

      @Override
      public CreateSchedule setFields(java.lang.String fields) {
        return (CreateSchedule) super.setFields(fields);
      }

      @Override
      public CreateSchedule setKey(java.lang.String key) {
        return (CreateSchedule) super.setKey(key);
      }

      @Override
      public CreateSchedule setOauthToken(java.lang.String oauthToken) {
        return (CreateSchedule) super.setOauthToken(oauthToken);
      }

      @Override
      public CreateSchedule setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (CreateSchedule) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public CreateSchedule setQuotaUser(java.lang.String quotaUser) {
        return (CreateSchedule) super.setQuotaUser(quotaUser);
      }

      @Override
      public CreateSchedule setUserIp(java.lang.String userIp) {
        return (CreateSchedule) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long startTime;

      /**

       */
      public java.lang.Long getStartTime() {
        return startTime;
      }

      public CreateSchedule setStartTime(java.lang.Long startTime) {
        this.startTime = startTime;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.Long finishTime;

      /**

       */
      public java.lang.Long getFinishTime() {
        return finishTime;
      }

      public CreateSchedule setFinishTime(java.lang.Long finishTime) {
        this.finishTime = finishTime;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.String email;

      /**

       */
      public java.lang.String getEmail() {
        return email;
      }

      public CreateSchedule setEmail(java.lang.String email) {
        this.email = email;
        return this;
      }

      @Override
      public CreateSchedule set(String parameterName, Object value) {
        return (CreateSchedule) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "scheduleV1EndPoint.getSchedule".
     *
     * This request holds the parameters needed by the the scheduleEndpoint server.  After setting any
     * optional parameters, call the {@link GetSchedule#execute()} method to invoke the remote
     * operation.
     *
     * @param startTime
     * @param finishTime
     * @param email
     * @return the request
     */
    public GetSchedule getSchedule(java.lang.Long startTime, java.lang.Long finishTime, java.lang.String email) throws java.io.IOException {
      GetSchedule result = new GetSchedule(startTime, finishTime, email);
      initialize(result);
      return result;
    }

    public class GetSchedule extends ScheduleEndpointRequest<com.google.api.services.scheduleEndpoint.model.ScheduleV1DtoCollection> {

      private static final String REST_PATH = "schedulev1dtocollection/{startTime}/{finishTime}/{email}";

      /**
       * Create a request for the method "scheduleV1EndPoint.getSchedule".
       *
       * This request holds the parameters needed by the the scheduleEndpoint server.  After setting any
       * optional parameters, call the {@link GetSchedule#execute()} method to invoke the remote
       * operation. <p> {@link
       * GetSchedule#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param startTime
       * @param finishTime
       * @param email
       * @since 1.13
       */
      protected GetSchedule(java.lang.Long startTime, java.lang.Long finishTime, java.lang.String email) {
        super(ScheduleEndpoint.this, "GET", REST_PATH, null, com.google.api.services.scheduleEndpoint.model.ScheduleV1DtoCollection.class);
        this.startTime = com.google.api.client.util.Preconditions.checkNotNull(startTime, "Required parameter startTime must be specified.");
        this.finishTime = com.google.api.client.util.Preconditions.checkNotNull(finishTime, "Required parameter finishTime must be specified.");
        this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetSchedule setAlt(java.lang.String alt) {
        return (GetSchedule) super.setAlt(alt);
      }

      @Override
      public GetSchedule setFields(java.lang.String fields) {
        return (GetSchedule) super.setFields(fields);
      }

      @Override
      public GetSchedule setKey(java.lang.String key) {
        return (GetSchedule) super.setKey(key);
      }

      @Override
      public GetSchedule setOauthToken(java.lang.String oauthToken) {
        return (GetSchedule) super.setOauthToken(oauthToken);
      }

      @Override
      public GetSchedule setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetSchedule) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetSchedule setQuotaUser(java.lang.String quotaUser) {
        return (GetSchedule) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetSchedule setUserIp(java.lang.String userIp) {
        return (GetSchedule) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long startTime;

      /**

       */
      public java.lang.Long getStartTime() {
        return startTime;
      }

      public GetSchedule setStartTime(java.lang.Long startTime) {
        this.startTime = startTime;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.Long finishTime;

      /**

       */
      public java.lang.Long getFinishTime() {
        return finishTime;
      }

      public GetSchedule setFinishTime(java.lang.Long finishTime) {
        this.finishTime = finishTime;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.String email;

      /**

       */
      public java.lang.String getEmail() {
        return email;
      }

      public GetSchedule setEmail(java.lang.String email) {
        this.email = email;
        return this;
      }

      @Override
      public GetSchedule set(String parameterName, Object value) {
        return (GetSchedule) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link ScheduleEndpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link ScheduleEndpoint}. */
    @Override
    public ScheduleEndpoint build() {
      return new ScheduleEndpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ScheduleEndpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setScheduleEndpointRequestInitializer(
        ScheduleEndpointRequestInitializer scheduleendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(scheduleendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
